[Base]
base_url= 'https://ke41.ulticlock.com/UtmOdataServices/api/'
username= 'EnterUserName'
password= 'EnterPassWord'
[primary_endpoints]
Employee= "EmpId"
Time = ""
[attribute_endpoints]
"OrgLevel1" = "OrgLevel1Id"
"OrgLevel2" = "OrgLevel2Id"
"OrgLevel3" = "OrgLevel3Id"
"Orglevel4" = "OrgLevel4Id"
"Location" = "LocationId"
#"PayCode"
#"PayGroup"
#"PayMatrix"
#"PayType"
"Project" = "ProjectId"
#"Reason" = "ReasonId"
#    "Shift"
#    "ShiftDet"
#    "ShiftLvl"
"Job" = "JobId"
#    "Time"
#    "Schedule"
#    "ScheduleRequest"
#    "Timesheet"
