[UTM_Base]
base_url= 'https://ke41.ulticlock.com/UtmOdataServices/api'
[primary_endpoints]
Employee= "EmpId"
Time = ""
[attribute_endpoints]
"OrgLevel1" = "OrgLevel1Id"
"OrgLevel2" = "OrgLevel2Id"
"OrgLevel3" = "OrgLevel3Id"
"OrgLevel4" = "OrgLevel4Id"
"Location" = "LocationId"
#"PayCode"
"Paygroup" = "PaygroupId"
#"PayMatrix"
#"PayType"
"Project" = "ProjectId"
#"Reason" = "ReasonId"
#    "Shift"
#    "ShiftDet"
#    "ShiftLvl"
"Job" = "JobId"
#    "Time"
#    "Schedule"
#    "ScheduleRequest"
#    "Timesheet"
[CMiC_Base]
host_url = 'https://nova-api.cmiccloud.com/cmicprod'
#host_url = 'https://nova-api-test.cmiccloud.com/cmictest'